version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: redis-dev
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  redis-commander:
    image: rediscommander/redis-commander
    ports:
      - "8081:8081"
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379
  prometheus:
      image: prom/prometheus
      container_name: prometheus-dev
      ports:
        - "9090:9090"
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana-oss
    container_name: grafana-dev
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
volumes:
  redis-data:
  grafana-data: