spring.application.name=fwitch
server.port=${FWITCH_SERVER_PORT:8080}
server.servlet.context-path=${FWITCH_SERVER_CONTEXT_PATH:/}
fwitch.data.root.folder=${FWITCH_DATA_ROOT:./fwitch_data}
logging.file.name=${fwitch.data.root.folder}/logs/fwitch.log
spring.redis.host=${FWITCH_REDIS_HOST:localhost}
spring.data.redis.port=${FWITCH_REDIS_PORT:6379}
xspring.redis.password=${FWITCH_REDIS_PASSWORD:manishelf-redis}
spring.docker.compose.enabled=true
spring.docker.compose.lifecycle-management=start_and_stop
spring.docker.compose.file=docker-compose.yml
logging.level.org.springframework.boot.docker.compose=DEBUG

management.endpoints.web.exposure.include=prometheus,health,info
management.endpoints.prometheus.enabled=true


